import { z } from "zod";
import { chapterStatusValues, promptTemplateKeyValues, stepKeyValues } from "../../lib/novel-db/schema";
import { CHAPTER_TITLE_MAX_LENGTH } from "./chapter-title";

const required = z.string().trim().min(1, "此项不能为空");
const tenChapterStart = z.number().int().refine((value) => [1, 11, 21, 31, 41, 51].includes(value), "章节批次必须从1、11、21、31、41或51开始");
export const createNovelSchema = z.object({ name: required.max(100), referenceTitle: required.max(200), referenceSummary: required.max(50_000), schemeId: z.string().optional() });
export const updateNovelSchema = z.object({ novelId: required, name: required.optional(), selectedTopic: z.string().optional(), firstVolumeOutline: z.string().optional(), currentStep: z.enum(stepKeyValues).optional(), currentRangeStart: z.number().int().min(1).max(51).refine((value) => (value - 1) % 10 === 0).optional(), currentChapter: z.number().int().min(1).max(60).optional() });
export const saveWorkPositionSchema = updateNovelSchema.pick({ novelId: true, currentStep: true, currentRangeStart: true, currentChapter: true }).required();
export const saveStepSchema = z.object({ novelId: required, key: z.enum(stepKeyValues), content: z.string(), draft: z.boolean() });
export const saveUnitSchema = z.object({ novelId: required, startChapter: tenChapterStart, content: z.string(), draft: z.boolean() });
export const saveOutlineSchema = z.object({ novelId: required, chapterNumber: z.number().int().min(1).max(60), content: z.string(), draft: z.boolean() });
export const saveOutlineBatchSchema = z.object({ novelId: required, startChapter: tenChapterStart, content: z.string(), draft: z.boolean() });
export const saveChapterSchema = z.object({ novelId: required, chapterNumber: z.number().int().min(1).max(60), title: z.string().trim().max(CHAPTER_TITLE_MAX_LENGTH).default(""), content: z.string(), status: z.enum(chapterStatusValues), draft: z.boolean() });
export const updateChapterStatusSchema = z.object({ novelId: required, chapterNumber: z.number().int().min(1).max(60), status: z.enum(["saved", "published"]) });
export const chapterTaskSchema = z.object({ novelId: required, chapterNumber: z.number().int().min(1).max(60) });
export const createChapterAutomationSchema = z.object({ novelId: required, startChapter: z.number().int().min(1).max(60), chapterCount: z.number().int().min(1).max(10) });
export const importCodexChapterSchema = chapterTaskSchema.extend({ expectedUpdatedAt: z.number({ error: "章节更新时间无效，请重新读取正文" }).int().nullable(), expectedDatabaseTitle: z.string(), expectedDatabaseContent: z.string(), expectedFileTitle: z.string(), expectedFileContent: z.string(), expectedContinuitySummary: z.string().optional(), expectedContinuityState: z.string().optional(), expectedContinuityRunId: z.string().optional() });
export const updateTemplateSchema = z.object({ novelId: required, key: z.enum(promptTemplateKeyValues), template: required });
export const restoreContentVersionSchema = z.object({ novelId: required, versionId: required });
export const setNovelSchemeSchema = z.object({ novelId: required, schemeId: required });
export const createSchemeSchema = z.object({ name: required.max(100), description: z.string().max(5000), sourceSchemeId: required.optional() });
export const saveSchemeSchema = z.object({ id: required, name: required.max(100), description: z.string().max(5000) });
export const saveSchemeTemplateSchema = z.object({ id: required, key: z.enum(promptTemplateKeyValues), template: required });
export const idSchema = required;
